-
  id: 1
  addr: localhost:8001
  heartbeat_interval: 5000
  heartbeat_check_interval: 6000
  max_election_timeout: 40000
-
  id: 2
  addr: localhost:8002
  heartbeat_interval: 5000
  heartbeat_check_interval: 6000
  max_election_timeout: 40000
-
  id: 3
  addr: localhost:8003
  heartbeat_interval: 5000
  heartbeat_check_interval: 6000
  max_election_timeout: 40000

