-
  id: 1
  addr: localhost:8001
  heartbeat_interval: 1000
  heartbeat_check_interval: 3000
  max_election_timeout: 30000
-
  id: 2
  addr: localhost:8002
  heartbeat_interval: 1000
  heartbeat_check_interval: 3000
  max_election_timeout: 30000
-
  id: 3
  addr: localhost:8003
  heartbeat_interval: 1000
  heartbeat_check_interval: 3000
  max_election_timeout: 30000

